stages:
  - name: Install Dependencies
    type: npm
    script: |
      npm install
      cds build

  - name: Build MTA
    type: mtaBuild
    parameters:
      mtaFile: mta.yaml

  - name: Deploy to Cloud Foundry
    type: cloudFoundryDeploy
    parameters:
      apiEndpoint: https://api.cf.us10-001.hana.ondemand.com
      org: 90cfb10ftrial
      space: dev
      credentialsId: cf
      mtaPath: mta_archives/*.mtar
