/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseOrder_ERP1ObjectPageObjectPage journey");

        opaTest("Navigate to PurchaseOrder_ERP1ObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThePurchaseOrder_ERP1List.onFilterBar().iExecuteSearch();

            Then.onThePurchaseOrder_ERP1List.onTable().iCheckRows();
            When.onThePurchaseOrder_ERP1List.onTable().iPressRow(0);

            Then.onThePurchaseOrder_ERP1ObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePurchaseOrder_ERP1ObjectPage.iCheckSection({ section: "FieldGroup::MainDetails" });
            Then.onThePurchaseOrder_ERP1ObjectPage.onForm({ section: "FieldGroup::MainDetails" }).iCheckField({ property: "RSPONumber" });
            Then.onThePurchaseOrder_ERP1ObjectPage.onForm({ section: "FieldGroup::MainDetails" }).iCheckField({ property: "RSPOLineItemNumber" });
            Then.onThePurchaseOrder_ERP1ObjectPage.onForm({ section: "FieldGroup::MainDetails" }).iCheckField({ property: "DeliveryDate" });
            Then.onThePurchaseOrder_ERP1ObjectPage.onForm({ section: "FieldGroup::MainDetails" }).iCheckField({ property: "Status" });
            Then.onThePurchaseOrder_ERP1ObjectPage.onForm({ section: "FieldGroup::MainDetails" }).iCheckField({ property: "Quantity" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});